### ISSUE TITLE
Add Apollo

### ISSUE THREAD

**Issue by jolo-dev** [frandiox/vitesse-ssr-template#10]
Hello,

I have trouble adding [VueApollo](https://apollo.vuejs.org/guide/installation.html).
I am quite new to Vue3.

Thanks in advanced.

**Comment by frandiox** [comment]
Hello! Vue-Apollo for Vue 3 is in alpha version and has some bugs, so I'm not sure if it works well.

That said, you can see an example here: https://github.com/frandiox/vite-ssr/blob/vue-apollo/examples/vue-apollo/src/main.js

It won't await for the queries in SSR automatically due to a vue-apollo bug, but you can make your own workaround until that package is fixed I guess: https://github.com/vuejs/vue-apollo/issues/1100


Otherwise, you might be more lucky with [urql client](https://github.com/FormidableLabs/urql).

**Comment by jolo-dev** [comment]
@frandiox oh wow. Thanks for your reply. I owe you! :)
